=== JosePonferrada/EjerciciosLMSGI/videoclub.dtd
<!ELEMENT videoclub ANY>
<!ELEMENT articulos (peliculas | juegos)*>
<!ELEMENT peliculas (#PCDATA | pelicula)*>
<!ELEMENT pelicula (titulo, genero, estreno?, (disponible | alquilada))>
<!ELEMENT juegos (juego, (disponible | alquilada))+>
<!ELEMENT juego ANY>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT estreno (#PCDATA)>
<!ELEMENT disponible EMPTY>
<!ELEMENT alquilada EMPTY>
<!ELEMENT codigoPelicula ANY>

<!ATTLIST videoclub direccion CDATA #IMPLIED
                    nombre CDATA #REQUIRED
                    telefono CDATA #FIXED "957525112">
<!ATTLIST pelicula codigo ID #REQUIRED>
<!ATTLIST pelicula codigoPelicula IDREF #REQUIRED
                    ofertaPelicula IDREFS #IMPLIED>
                                    
<!ATTLIST articulos codigo ID #REQUIRED>
<!ENTITY top "Â¡TOP ESTA SEMANA!">
<!ENTITY % atributoCoste "coste CDATA #IMPLIED">
<!ATTLIST pelicula %atributoCoste;>

=== JosePonferrada/EjerciciosLMSGI/videoclub.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videoclub SYSTEM "videoclub.dtd">
<videoclub direccion="Parque Europa" nombre="El Perro Loco" telefono="957525112">
    <peliculas> 
        <pelicula codigoPelicula="pel001" coste="5"> 
            <titulo>La milla verde</titulo>
            <genero>Drama/Crimen</genero>
            <estreno/>
            <disponible/>
        </pelicula>
        <pelicula codigoPelicula="pel033">
            <titulo></titulo>
            <genero></genero>
            <alquilada/>
        </pelicula> 
    </peliculas>
    <juegos>
        <juego>FC 24 &top;</juego>
        <disponible/>
    </juegos>
</videoclub>
