=== JosePonferrada/EjerciciosLMSGI/DTD/equipoBaloncesto.dtd
<!ELEMENT equipoBaloncesto (entrenador, jugador+)>
<!ELEMENT entrenador (nombreEntrenador, edad)>
<!ELEMENT jugador (nombreJugador, numeroDorsal, (rookie | veterano)?)>
<!ELEMENT nombreEntrenador (#PCDATA)>
<!ELEMENT edad (#PCDATA | fechaNacimiento)*>
<!ELEMENT fechaNacimiento (#PCDATA)>
<!ELEMENT nombreJugador (#PCDATA)>
<!ELEMENT numeroDorsal (#PCDATA)>
<!ELEMENT rookie EMPTY>
<!ELEMENT veterano EMPTY>

<!ATTLIST equipoBaloncesto nombreEquipo CDATA #REQUIRED
                            ciudad CDATA #FIXED "Wayhaven City"
                            codigoMiembrosEquipo IDREFS #IMPLIED>
<!ATTLIST entrenador codigo ID #REQUIRED
                        titulosGanados CDATA #IMPLIED>
<!ATTLIST jugador posicion (base | escolta | alero | ala-pivot | pivot) "base"
                    codigo ID #REQUIRED
                    codigoEntrenador IDREF #IMPLIED>

<!ENTITY alias "-Ricky-">
<!ENTITY % atributoAltura "altura CDATA #IMPLIED">
<!ATTLIST jugador %atributoAltura;>
<!ATTLIST entrenador %atributoAltura;>

=== JosePonferrada/EjerciciosLMSGI/equipoBaloncesto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipoBaloncesto SYSTEM "equipoBaloncesto.dtd">
<equipoBaloncesto nombreEquipo="Wayhaven Warriors" ciudad="Wayhaven City"
codigoMiembrosEquipo="RicGom MarJor FerVil">

    <entrenador codigo="RicGom" titulosGanados="3" altura="195">
        <nombreEntrenador>Ricardo &alias; GÃ³mez Smith</nombreEntrenador>
        <edad>42
            <fechaNacimiento>17/09/1981</fechaNacimiento>
        </edad>
    </entrenador>

    <jugador codigo="MarJor" codigoEntrenador="RicGom" posicion="base" altura="203">
        <nombreJugador>Marcus Jordan</nombreJugador>
        <numeroDorsal>97</numeroDorsal>
        <rookie/>
    </jugador>

    <jugador codigo="FerVil" codigoEntrenador="RicGom" posicion="ala-pivot" altura="211">
        <nombreJugador>Fernando Villanova</nombreJugador>
        <numeroDorsal>21</numeroDorsal>
    </jugador>

</equipoBaloncesto>
