=== JosePonferrada/EjerciciosLMSGI/DTD/examenDTD.dtd
<!ELEMENT exposiciones (#PCDATA | exposicion)*>
<!ELEMENT exposicion (fecha, obra+, artista?, (vivo | muerto)?)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT obra (#PCDATA)>
<!ELEMENT artista (#PCDATA)>
<!ELEMENT vivo EMPTY>
<!ELEMENT muerto (#PCDATA)>
<!ENTITY % attNombre "nombre CDATA #REQUIRED">

<!ATTLIST exposiciones %attNombre;
                    ciudad (Fuengirola | Córdoba | Valencia) "Fuengirola"
                    webVentaEntradas CDATA #FIXED "www.entradas.com"
                    empresaViajes CDATA #IMPLIED>

<!ATTLIST obra nombre ID #IMPLIED>
<!ATTLIST artista obraRealizada IDREF #IMPLIED>
<!ATTLIST exposicion obras IDREFS #IMPLIED
                    nombre CDATA #IMPLIED>
<!ENTITY oferta "El precio de esta entrada está rebajado a la mitad.">

=== JosePonferrada/EjerciciosLMSGI/examenDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE exposiciones SYSTEM "examenDTD.dtd">
<exposiciones nombre="Exposiciones S.L." webVentaEntradas="www.entradas.com" empresaViajes="ALSA">Las mejores exposiciones del país
  <exposicion nombre="Exposición del lunes" obras="men gue">
    <fecha>Lunes, 10 de julio</fecha>
    <obra nombre="men">Las 3 meninas</obra>
    <artista obraRealizada="men">Julián</artista>
    <vivo></vivo>
  </exposicion>  
  <exposicion obras="men gue">
    <fecha>Lunes, 10 de julio</fecha>
    <obra nombre="gue">Guernika</obra>
    <artista obraRealizada="gue">Pablo</artista>
    <muerto>Murió hace 12 años</muerto>
  </exposicion>
  <exposicion obras="pam">
    <fecha>Jueves, 15 de agosto</fecha>
    <obra nombre="pam">Pamplona a los 4 vientos. &oferta;</obra>
    <artista></artista>
  </exposicion>
  <exposicion>
    <fecha>Jueves, 15 de agosto</fecha>
    <obra nombre="luc">Lucena al sol. &oferta;</obra>
    <artista></artista>
  </exposicion>
</exposiciones>
